version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booklist
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./booklist-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/booklist
      - REDIS_URL=redis://redis:6379/0  

    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./booklist-front
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: ./booklist-backend
    command: celery -A celery_worker worker --loglevel=info
    depends_on:
      - backend
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:admin@db:5432/booklist
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data: 