backend:
  runs-on: ubuntu-latest
  services:
    postgres:
      image: postgres:13
      env:
        POSTGRES_DB: booklist
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
      ports:
        - 5432:5432
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

  defaults:
    run:
      working-directory: ./booklist-backend

  steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Wait for Postgres to be ready
      run: sleep 10  # simple wait, optional

    - name: Run tests
      run: |
        if [ -f test_main.py ]; then pytest; else echo "No tests found"; fi

    - name: Show DB logs if failed
      if: failure()
      run: docker logs $(docker ps -aqf "ancestor=postgres:13")
